/**
 * @author orojas
 * This enum is used to classify tokens. 
 */
public enum TokenType {
	LETTER, IDENTIFIER,NUMBER,
	KEYWORD, SYMBOL, STRING, META_STATEMENT, MULT_OP, DIV_OP, PLUS, SEMI_COLON, COMMA,
	DOUBLE_AND, DOUBLE_OR, NOT, NEW_LINE,
	LEFT_PARAN, RIGHT_PARAN, EPSILON, WHITESPACE, LEFT_BRACE, RIGHT_BRACE,
	LEFT_BRACKET, RIGHT_BRACKET, MINUS, EMPTY, COMPARSION_OP, CONDITION_OP
}


